# NOTICE: Generated By HttpRunner. DO'NOT EDIT!
# FROM: testcases/demo_testcase_ref.yml
from httprunner import HttpRunner, TConfig, TStep


class TestCaseDemoTestcaseRef(HttpRunner):
    config = TConfig(
        **{
            "name": "request methods testcase: reference testcase",
            "variables": {"foo1": "session_bar1"},
            "base_url": "https://postman-echo.com",
            "verify": False,
            "path": "testcases/demo_testcase_ref_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "request with referenced testcase",
                "variables": {"foo1": "override_bar1"},
                "testcase": "testcases/demo_testcase_request.yml",
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcaseRef().test_start()
