# NOTICE: Generated By HttpRunner. DO'NOT EDIT!
# FROM: testcases/mubu.createdoc.yml
from httprunner import HttpRunner, TConfig, TStep


class TestCaseMubuCreatedoc(HttpRunner):
    config = TConfig(
        **{
            "name": "testcase description",
            "variables": {
                "user_phone": "18613143458",
                "password": "moFrwx$!kz3DTRm@@*aV",
            },
            "verify": False,
            "path": "testcases/mubu_createdoc_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "/",
                "request": {
                    "headers": {
                        "cookie": "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1589703642",
                        "sec-fetch-dest": "document",
                        "sec-fetch-mode": "navigate",
                        "sec-fetch-site": "same-origin",
                        "sec-fetch-user": "?1",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                    },
                    "method": "GET",
                    "url": "https://mubu.com/",
                },
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "/login",
                "request": {
                    "headers": {
                        "cookie": "SLARDAR_WEB_ID=f1827e95-fc65-4b8f-b1a5-9b2bb5013426",
                        "referer": "https://mubu.com/",
                        "sec-fetch-dest": "document",
                        "sec-fetch-mode": "navigate",
                        "sec-fetch-site": "same-origin",
                        "sec-fetch-user": "?1",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                    },
                    "method": "GET",
                    "url": "https://mubu.com/login",
                },
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "/login/password",
                "request": {
                    "headers": {
                        "cookie": "reg_focusId=256b52a0-249c-45ef-bf0e-17221b8a5c3",
                        "referer": "https://mubu.com/login",
                        "sec-fetch-dest": "document",
                        "sec-fetch-mode": "navigate",
                        "sec-fetch-site": "same-origin",
                        "sec-fetch-user": "?1",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                    },
                    "method": "GET",
                    "url": "https://mubu.com/login/password",
                },
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "/api/login/submit",
                "request": {
                    "data": {
                        "password": "$password",
                        "phone": "$user_phone",
                        "remember": "true",
                    },
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                        "cookie": "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1589703649",
                        "referer": "https://mubu.com/login/password",
                        "sec-fetch-dest": "empty",
                        "sec-fetch-mode": "cors",
                        "sec-fetch-site": "same-origin",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                        "x-requested-with": "XMLHttpRequest",
                    },
                    "method": "POST",
                    "url": "https://mubu.com/api/login/submit",
                },
                "validate": [
                    {"eq": ["status_code", 200]},
                    {"eq": ["body.code", 0]},
                    {"eq": ["body.msg", None]},
                ],
            }
        ),
        TStep(
            **{
                "name": "/list",
                "request": {
                    "headers": {
                        "cookie": "user_persistence=29ded4a9-2149-429b-a204-e24f86809f28",
                        "referer": "https://mubu.com/login/password",
                        "sec-fetch-dest": "document",
                        "sec-fetch-mode": "navigate",
                        "sec-fetch-site": "same-origin",
                        "sec-fetch-user": "?1",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                    },
                    "method": "GET",
                    "url": "https://mubu.com/list",
                },
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "/api/list/tip_new_update",
                "request": {
                    "data": "",
                    "headers": {
                        "cookie": "user_persistence=29ded4a9-2149-429b-a204-e24f86809f28",
                        "referer": "https://mubu.com/list",
                        "sec-fetch-dest": "empty",
                        "sec-fetch-mode": "cors",
                        "sec-fetch-site": "same-origin",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                        "x-requested-with": "XMLHttpRequest",
                    },
                    "method": "POST",
                    "url": "https://mubu.com/api/list/tip_new_update",
                },
                "validate": [
                    {"eq": ["status_code", 200]},
                    {"eq": ["body.code", 0]},
                    {"eq": ["body.msg", None]},
                ],
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreatedoc().test_start()
