# NOTICE: Generated By HttpRunner. DO'NOT EDIT!
# FROM: testcases/mubu.createdoc.yml
from httprunner import HttpRunner, TConfig, TStep


class TestCaseMubuCreatedoc(HttpRunner):
    config = TConfig(
        **{
            "name": "testcase description",
            "variables": {
                "user_phone": "18613143458",
                "password": "moFrwx$!kz3DTRm@@*aV",
            },
            "verify": False,
            "path": "testcases/mubu_createdoc_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "login mubu",
                "testcase": "testcases/mubu.login.yml",
                "export": ["user_persistence"],
            }
        ),
        TStep(
            **{
                "name": "/api/list/create_doc",
                "request": {
                    "data": {"folderId": "0", "type": "0"},
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                        "cookie": "user_persistence=$user_persistence",
                        "referer": "https://mubu.com/list",
                        "sec-fetch-dest": "empty",
                        "sec-fetch-mode": "cors",
                        "sec-fetch-site": "same-origin",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                        "x-requested-with": "XMLHttpRequest",
                    },
                    "method": "POST",
                    "url": "https://mubu.com/api/list/create_doc",
                },
                "extract": {"docId": "body.data.id"},
                "validate": [
                    {"eq": ["status_code", 200]},
                    {"eq": ["body.code", 0]},
                    {"eq": ["body.msg", None]},
                ],
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreatedoc().test_start()
